### ISSUE TITLE
SPACCa_conda_env_stable.yaml is empty

### ISSUE THREAD

**Issue by xyhua2000** [sebastian-gregoricchio/SPACCa#1]
Hi, when I try to create a conda environment using the SPACCa_conda_env_stable.yaml file, it indicates that the file is empty.

**Comment by sebastian-gregoricchio** [comment]
Hi! Indeed we are in the phase of repository building, so that's why some stuff is missing.  Now you should be able to see it.

Let me know if you encountered any issue.
